/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.contatos;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class JFrameListar extends javax.swing.JFrame {

    /**
     * Creates new form JFrameListar
     */
    public JFrameListar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    JFrameListar listar = new JFrameListar();
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbSobrenome3 = new javax.swing.JTextField();
        lbTelefone3 = new javax.swing.JTextField();
        lbEmail3 = new javax.swing.JTextField();
        lbNome3 = new javax.swing.JTextField();
        lbEmail4 = new javax.swing.JTextField();
        lbTelefone4 = new javax.swing.JTextField();
        lbSobrenome4 = new javax.swing.JTextField();
        lbNome4 = new javax.swing.JTextField();
        lbEmail5 = new javax.swing.JTextField();
        lbTeledone5 = new javax.swing.JTextField();
        lbSobrenome5 = new javax.swing.JTextField();
        lbNome5 = new javax.swing.JTextField();
        lbEmail6 = new javax.swing.JTextField();
        lbTeledone6 = new javax.swing.JTextField();
        lbSobrenome6 = new javax.swing.JTextField();
        lbNome6 = new javax.swing.JTextField();
        lbEmail7 = new javax.swing.JTextField();
        lbTeledone7 = new javax.swing.JTextField();
        lbSobrenome7 = new javax.swing.JTextField();
        lbNome7 = new javax.swing.JTextField();
        lbSobrenome12 = new javax.swing.JTextField();
        lbNome12 = new javax.swing.JTextField();
        lbSobrenome8 = new javax.swing.JTextField();
        lbTeledone8 = new javax.swing.JTextField();
        lbEmail8 = new javax.swing.JTextField();
        lbNome8 = new javax.swing.JTextField();
        lbEmail9 = new javax.swing.JTextField();
        lbTeledone9 = new javax.swing.JTextField();
        lbSobrenome9 = new javax.swing.JTextField();
        lbNome9 = new javax.swing.JTextField();
        lbEmail10 = new javax.swing.JTextField();
        lbTeledone10 = new javax.swing.JTextField();
        lbSobrenome10 = new javax.swing.JTextField();
        lbNome10 = new javax.swing.JTextField();
        lbEmail11 = new javax.swing.JTextField();
        lbTeledone11 = new javax.swing.JTextField();
        lbSobrenome11 = new javax.swing.JTextField();
        lbNome11 = new javax.swing.JTextField();
        lbEmail12 = new javax.swing.JTextField();
        lbTeledone12 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Aharoni", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(85, 107, 47));
        jLabel1.setText("Lista de contatos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nome");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Sobrenome");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Telefone");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Email");

        lbSobrenome3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbSobrenome3ActionPerformed(evt);
            }
        });

        lbTelefone3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbTelefone3ActionPerformed(evt);
            }
        });

        lbEmail3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbEmail3ActionPerformed(evt);
            }
        });

        lbNome3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbNome3ActionPerformed(evt);
            }
        });

        lbEmail4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbEmail4ActionPerformed(evt);
            }
        });

        lbTelefone4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbTelefone4ActionPerformed(evt);
            }
        });

        lbSobrenome4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbSobrenome4ActionPerformed(evt);
            }
        });

        lbNome4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbNome4ActionPerformed(evt);
            }
        });

        lbEmail5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbEmail5ActionPerformed(evt);
            }
        });

        lbTeledone5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbTeledone5ActionPerformed(evt);
            }
        });

        lbSobrenome5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbSobrenome5ActionPerformed(evt);
            }
        });

        lbNome5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbNome5ActionPerformed(evt);
            }
        });

        lbEmail6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbEmail6ActionPerformed(evt);
            }
        });

        lbTeledone6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbTeledone6ActionPerformed(evt);
            }
        });

        lbSobrenome6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbSobrenome6ActionPerformed(evt);
            }
        });

        lbNome6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbNome6ActionPerformed(evt);
            }
        });

        lbEmail7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbEmail7ActionPerformed(evt);
            }
        });

        lbTeledone7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbTeledone7ActionPerformed(evt);
            }
        });

        lbSobrenome7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbSobrenome7ActionPerformed(evt);
            }
        });

        lbNome7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbNome7ActionPerformed(evt);
            }
        });

        lbSobrenome12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbSobrenome12ActionPerformed(evt);
            }
        });

        lbNome12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbNome12ActionPerformed(evt);
            }
        });

        lbSobrenome8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbSobrenome8ActionPerformed(evt);
            }
        });

        lbTeledone8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbTeledone8ActionPerformed(evt);
            }
        });

        lbEmail8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbEmail8ActionPerformed(evt);
            }
        });

        lbNome8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbNome8ActionPerformed(evt);
            }
        });

        lbEmail9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbEmail9ActionPerformed(evt);
            }
        });

        lbTeledone9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbTeledone9ActionPerformed(evt);
            }
        });

        lbSobrenome9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbSobrenome9ActionPerformed(evt);
            }
        });

        lbNome9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbNome9ActionPerformed(evt);
            }
        });

        lbEmail10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbEmail10ActionPerformed(evt);
            }
        });

        lbTeledone10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbTeledone10ActionPerformed(evt);
            }
        });

        lbSobrenome10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbSobrenome10ActionPerformed(evt);
            }
        });

        lbNome10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbNome10ActionPerformed(evt);
            }
        });

        lbEmail11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbEmail11ActionPerformed(evt);
            }
        });

        lbTeledone11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbTeledone11ActionPerformed(evt);
            }
        });

        lbSobrenome11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbSobrenome11ActionPerformed(evt);
            }
        });

        lbNome11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbNome11ActionPerformed(evt);
            }
        });

        lbEmail12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbEmail12ActionPerformed(evt);
            }
        });

        lbTeledone12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbTeledone12ActionPerformed(evt);
            }
        });

        jButton1.setText("Fechar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(lbNome3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(lbSobrenome3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(211, 211, 211)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(207, 207, 207)
                                        .addComponent(lbEmail3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(lbTelefone3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNome4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(lbSobrenome4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(207, 207, 207)
                                        .addComponent(lbEmail4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(lbTelefone4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNome5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(lbSobrenome5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(207, 207, 207)
                                        .addComponent(lbEmail5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(lbTeledone5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNome6, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(lbSobrenome6, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(207, 207, 207)
                                        .addComponent(lbEmail6, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(lbTeledone6, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNome7, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(lbSobrenome7, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(207, 207, 207)
                                        .addComponent(lbEmail7, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(lbTeledone7, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNome8, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(lbSobrenome8, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(207, 207, 207)
                                        .addComponent(lbEmail8, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(lbTeledone8, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNome9, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(lbSobrenome9, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(207, 207, 207)
                                        .addComponent(lbEmail9, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(lbTeledone9, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNome10, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(lbSobrenome10, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(207, 207, 207)
                                        .addComponent(lbEmail10, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(lbTeledone10, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNome11, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(lbSobrenome11, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(207, 207, 207)
                                        .addComponent(lbEmail11, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(lbTeledone11, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNome12, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(lbSobrenome12, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(207, 207, 207)
                                        .addComponent(lbEmail12, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(lbTeledone12, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(240, 240, 240))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(275, 275, 275))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSobrenome3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTelefone3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSobrenome4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTelefone4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSobrenome5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTeledone5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSobrenome6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTeledone6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSobrenome7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTeledone7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSobrenome8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTeledone8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSobrenome9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTeledone9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSobrenome10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTeledone10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSobrenome11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTeledone11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSobrenome12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTeledone12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbSobrenome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbSobrenome3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSobrenome3ActionPerformed

    private void lbTelefone3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbTelefone3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbTelefone3ActionPerformed

    private void lbEmail3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbEmail3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbEmail3ActionPerformed

    private void lbNome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbNome3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbNome3ActionPerformed

    private void lbEmail4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbEmail4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbEmail4ActionPerformed

    private void lbTelefone4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbTelefone4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbTelefone4ActionPerformed

    private void lbSobrenome4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbSobrenome4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSobrenome4ActionPerformed

    private void lbNome4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbNome4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbNome4ActionPerformed

    private void lbEmail5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbEmail5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbEmail5ActionPerformed

    private void lbTeledone5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbTeledone5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbTeledone5ActionPerformed

    private void lbSobrenome5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbSobrenome5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSobrenome5ActionPerformed

    private void lbNome5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbNome5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbNome5ActionPerformed

    private void lbEmail6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbEmail6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbEmail6ActionPerformed

    private void lbTeledone6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbTeledone6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbTeledone6ActionPerformed

    private void lbSobrenome6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbSobrenome6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSobrenome6ActionPerformed

    private void lbNome6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbNome6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbNome6ActionPerformed

    private void lbEmail7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbEmail7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbEmail7ActionPerformed

    private void lbTeledone7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbTeledone7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbTeledone7ActionPerformed

    private void lbSobrenome7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbSobrenome7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSobrenome7ActionPerformed

    private void lbNome7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbNome7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbNome7ActionPerformed

    private void lbSobrenome12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbSobrenome12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSobrenome12ActionPerformed

    private void lbNome12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbNome12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbNome12ActionPerformed

    private void lbSobrenome8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbSobrenome8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSobrenome8ActionPerformed

    private void lbTeledone8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbTeledone8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbTeledone8ActionPerformed

    private void lbEmail8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbEmail8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbEmail8ActionPerformed

    private void lbNome8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbNome8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbNome8ActionPerformed

    private void lbEmail9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbEmail9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbEmail9ActionPerformed

    private void lbTeledone9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbTeledone9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbTeledone9ActionPerformed

    private void lbSobrenome9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbSobrenome9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSobrenome9ActionPerformed

    private void lbNome9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbNome9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbNome9ActionPerformed

    private void lbEmail10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbEmail10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbEmail10ActionPerformed

    private void lbTeledone10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbTeledone10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbTeledone10ActionPerformed

    private void lbSobrenome10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbSobrenome10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSobrenome10ActionPerformed

    private void lbNome10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbNome10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbNome10ActionPerformed

    private void lbEmail11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbEmail11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbEmail11ActionPerformed

    private void lbTeledone11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbTeledone11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbTeledone11ActionPerformed

    private void lbSobrenome11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbSobrenome11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSobrenome11ActionPerformed

    private void lbNome11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbNome11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbNome11ActionPerformed

    private void lbEmail12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbEmail12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbEmail12ActionPerformed

    private void lbTeledone12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbTeledone12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbTeledone12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameListar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField lbEmail10;
    private javax.swing.JTextField lbEmail11;
    private javax.swing.JTextField lbEmail12;
    private javax.swing.JTextField lbEmail3;
    private javax.swing.JTextField lbEmail4;
    private javax.swing.JTextField lbEmail5;
    private javax.swing.JTextField lbEmail6;
    private javax.swing.JTextField lbEmail7;
    private javax.swing.JTextField lbEmail8;
    private javax.swing.JTextField lbEmail9;
    private javax.swing.JTextField lbNome10;
    private javax.swing.JTextField lbNome11;
    private javax.swing.JTextField lbNome12;
    private javax.swing.JTextField lbNome3;
    private javax.swing.JTextField lbNome4;
    private javax.swing.JTextField lbNome5;
    private javax.swing.JTextField lbNome6;
    private javax.swing.JTextField lbNome7;
    private javax.swing.JTextField lbNome8;
    private javax.swing.JTextField lbNome9;
    private javax.swing.JTextField lbSobrenome10;
    private javax.swing.JTextField lbSobrenome11;
    private javax.swing.JTextField lbSobrenome12;
    private javax.swing.JTextField lbSobrenome3;
    private javax.swing.JTextField lbSobrenome4;
    private javax.swing.JTextField lbSobrenome5;
    private javax.swing.JTextField lbSobrenome6;
    private javax.swing.JTextField lbSobrenome7;
    private javax.swing.JTextField lbSobrenome8;
    private javax.swing.JTextField lbSobrenome9;
    private javax.swing.JTextField lbTeledone10;
    private javax.swing.JTextField lbTeledone11;
    private javax.swing.JTextField lbTeledone12;
    private javax.swing.JTextField lbTeledone5;
    private javax.swing.JTextField lbTeledone6;
    private javax.swing.JTextField lbTeledone7;
    private javax.swing.JTextField lbTeledone8;
    private javax.swing.JTextField lbTeledone9;
    private javax.swing.JTextField lbTelefone3;
    private javax.swing.JTextField lbTelefone4;
    // End of variables declaration//GEN-END:variables
}
